/* automatically generated by rust-bindgen 0.73.2 */

pub type CUdeviceptr_v2 = ::std::os::raw::c_ulonglong;
pub type CUdeviceptr = CUdeviceptr_v2;
pub type CUdevice_v1 = ::std::os::raw::c_int;
pub type CUdevice = CUdevice_v1;
#[repr(C)]
#[derive(Debug)]
pub struct CUctx_st {
    _unused: [u8; 0],
}
pub type CUcontext = *mut CUctx_st;
#[repr(C)]
#[derive(Debug)]
pub struct CUarray_st {
    _unused: [u8; 0],
}
pub type CUarray = *mut CUarray_st;
#[repr(C)]
#[derive(Debug)]
pub struct CUmipmappedArray_st {
    _unused: [u8; 0],
}
pub type CUmipmappedArray = *mut CUmipmappedArray_st;
#[repr(C)]
#[derive(Debug)]
pub struct CUstream_st {
    _unused: [u8; 0],
}
pub type CUstream = *mut CUstream_st;
pub type CUtexObject_v1 = ::std::os::raw::c_ulonglong;
pub type CUtexObject = CUtexObject_v1;
#[repr(C)]
#[derive(Debug)]
pub struct CUextMemory_st {
    _unused: [u8; 0],
}
pub type CUexternalMemory = *mut CUextMemory_st;
#[repr(C)]
#[derive(Debug)]
pub struct CUextSemaphore_st {
    _unused: [u8; 0],
}
pub type CUexternalSemaphore = *mut CUextSemaphore_st;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUuuid_st {
    pub bytes: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUuuid_st"][::std::mem::size_of::<CUuuid_st>() - 16usize];
    ["Alignment of CUuuid_st"][::std::mem::align_of::<CUuuid_st>() - 1usize];
    ["Offset of field: CUuuid_st::bytes"][::std::mem::offset_of!(CUuuid_st, bytes) - 0usize];
};
pub type CUuuid = CUuuid_st;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUarray_format_enum {
    CU_AD_FORMAT_UNSIGNED_INT8 = 1,
    CU_AD_FORMAT_UNSIGNED_INT16 = 2,
    CU_AD_FORMAT_UNSIGNED_INT32 = 3,
    CU_AD_FORMAT_SIGNED_INT8 = 8,
    CU_AD_FORMAT_SIGNED_INT16 = 9,
    CU_AD_FORMAT_SIGNED_INT32 = 10,
    CU_AD_FORMAT_HALF = 16,
    CU_AD_FORMAT_FLOAT = 32,
    CU_AD_FORMAT_NV12 = 176,
    CU_AD_FORMAT_UNORM_INT8X1 = 192,
    CU_AD_FORMAT_UNORM_INT8X2 = 193,
    CU_AD_FORMAT_UNORM_INT8X4 = 194,
    CU_AD_FORMAT_UNORM_INT16X1 = 195,
    CU_AD_FORMAT_UNORM_INT16X2 = 196,
    CU_AD_FORMAT_UNORM_INT16X4 = 197,
    CU_AD_FORMAT_SNORM_INT8X1 = 198,
    CU_AD_FORMAT_SNORM_INT8X2 = 199,
    CU_AD_FORMAT_SNORM_INT8X4 = 200,
    CU_AD_FORMAT_SNORM_INT16X1 = 201,
    CU_AD_FORMAT_SNORM_INT16X2 = 202,
    CU_AD_FORMAT_SNORM_INT16X4 = 203,
    CU_AD_FORMAT_BC1_UNORM = 145,
    CU_AD_FORMAT_BC1_UNORM_SRGB = 146,
    CU_AD_FORMAT_BC2_UNORM = 147,
    CU_AD_FORMAT_BC2_UNORM_SRGB = 148,
    CU_AD_FORMAT_BC3_UNORM = 149,
    CU_AD_FORMAT_BC3_UNORM_SRGB = 150,
    CU_AD_FORMAT_BC4_UNORM = 151,
    CU_AD_FORMAT_BC4_SNORM = 152,
    CU_AD_FORMAT_BC5_UNORM = 153,
    CU_AD_FORMAT_BC5_SNORM = 154,
    CU_AD_FORMAT_BC6H_UF16 = 155,
    CU_AD_FORMAT_BC6H_SF16 = 156,
    CU_AD_FORMAT_BC7_UNORM = 157,
    CU_AD_FORMAT_BC7_UNORM_SRGB = 158,
}
pub use self::CUarray_format_enum as CUarray_format;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUaddress_mode_enum {
    CU_TR_ADDRESS_MODE_WRAP = 0,
    CU_TR_ADDRESS_MODE_CLAMP = 1,
    CU_TR_ADDRESS_MODE_MIRROR = 2,
    CU_TR_ADDRESS_MODE_BORDER = 3,
}
pub use self::CUaddress_mode_enum as CUaddress_mode;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUfilter_mode_enum {
    CU_TR_FILTER_MODE_POINT = 0,
    CU_TR_FILTER_MODE_LINEAR = 1,
}
pub use self::CUfilter_mode_enum as CUfilter_mode;
impl CUmemorytype_enum {
    pub const CU_MEMORYTYPE_HOST: CUmemorytype_enum = CUmemorytype_enum(1);
    pub const CU_MEMORYTYPE_DEVICE: CUmemorytype_enum = CUmemorytype_enum(2);
    pub const CU_MEMORYTYPE_ARRAY: CUmemorytype_enum = CUmemorytype_enum(3);
    pub const CU_MEMORYTYPE_UNIFIED: CUmemorytype_enum = CUmemorytype_enum(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUmemorytype_enum(pub ::std::os::raw::c_uint);
pub use self::CUmemorytype_enum as CUmemorytype;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUresourcetype_enum {
    CU_RESOURCE_TYPE_ARRAY = 0,
    CU_RESOURCE_TYPE_MIPMAPPED_ARRAY = 1,
    CU_RESOURCE_TYPE_LINEAR = 2,
    CU_RESOURCE_TYPE_PITCH2D = 3,
}
pub use self::CUresourcetype_enum as CUresourcetype;
impl cudaError_enum {
    pub const CUDA_SUCCESS: cudaError_enum = cudaError_enum(0);
    pub const CUDA_ERROR_INVALID_VALUE: cudaError_enum = cudaError_enum(1);
    pub const CUDA_ERROR_OUT_OF_MEMORY: cudaError_enum = cudaError_enum(2);
    pub const CUDA_ERROR_NOT_INITIALIZED: cudaError_enum = cudaError_enum(3);
    pub const CUDA_ERROR_DEINITIALIZED: cudaError_enum = cudaError_enum(4);
    pub const CUDA_ERROR_PROFILER_DISABLED: cudaError_enum = cudaError_enum(5);
    pub const CUDA_ERROR_PROFILER_NOT_INITIALIZED: cudaError_enum = cudaError_enum(6);
    pub const CUDA_ERROR_PROFILER_ALREADY_STARTED: cudaError_enum = cudaError_enum(7);
    pub const CUDA_ERROR_PROFILER_ALREADY_STOPPED: cudaError_enum = cudaError_enum(8);
    pub const CUDA_ERROR_STUB_LIBRARY: cudaError_enum = cudaError_enum(34);
    pub const CUDA_ERROR_DEVICE_UNAVAILABLE: cudaError_enum = cudaError_enum(46);
    pub const CUDA_ERROR_NO_DEVICE: cudaError_enum = cudaError_enum(100);
    pub const CUDA_ERROR_INVALID_DEVICE: cudaError_enum = cudaError_enum(101);
    pub const CUDA_ERROR_DEVICE_NOT_LICENSED: cudaError_enum = cudaError_enum(102);
    pub const CUDA_ERROR_INVALID_IMAGE: cudaError_enum = cudaError_enum(200);
    pub const CUDA_ERROR_INVALID_CONTEXT: cudaError_enum = cudaError_enum(201);
    pub const CUDA_ERROR_CONTEXT_ALREADY_CURRENT: cudaError_enum = cudaError_enum(202);
    pub const CUDA_ERROR_MAP_FAILED: cudaError_enum = cudaError_enum(205);
    pub const CUDA_ERROR_UNMAP_FAILED: cudaError_enum = cudaError_enum(206);
    pub const CUDA_ERROR_ARRAY_IS_MAPPED: cudaError_enum = cudaError_enum(207);
    pub const CUDA_ERROR_ALREADY_MAPPED: cudaError_enum = cudaError_enum(208);
    pub const CUDA_ERROR_NO_BINARY_FOR_GPU: cudaError_enum = cudaError_enum(209);
    pub const CUDA_ERROR_ALREADY_ACQUIRED: cudaError_enum = cudaError_enum(210);
    pub const CUDA_ERROR_NOT_MAPPED: cudaError_enum = cudaError_enum(211);
    pub const CUDA_ERROR_NOT_MAPPED_AS_ARRAY: cudaError_enum = cudaError_enum(212);
    pub const CUDA_ERROR_NOT_MAPPED_AS_POINTER: cudaError_enum = cudaError_enum(213);
    pub const CUDA_ERROR_ECC_UNCORRECTABLE: cudaError_enum = cudaError_enum(214);
    pub const CUDA_ERROR_UNSUPPORTED_LIMIT: cudaError_enum = cudaError_enum(215);
    pub const CUDA_ERROR_CONTEXT_ALREADY_IN_USE: cudaError_enum = cudaError_enum(216);
    pub const CUDA_ERROR_PEER_ACCESS_UNSUPPORTED: cudaError_enum = cudaError_enum(217);
    pub const CUDA_ERROR_INVALID_PTX: cudaError_enum = cudaError_enum(218);
    pub const CUDA_ERROR_INVALID_GRAPHICS_CONTEXT: cudaError_enum = cudaError_enum(219);
    pub const CUDA_ERROR_NVLINK_UNCORRECTABLE: cudaError_enum = cudaError_enum(220);
    pub const CUDA_ERROR_JIT_COMPILER_NOT_FOUND: cudaError_enum = cudaError_enum(221);
    pub const CUDA_ERROR_UNSUPPORTED_PTX_VERSION: cudaError_enum = cudaError_enum(222);
    pub const CUDA_ERROR_JIT_COMPILATION_DISABLED: cudaError_enum = cudaError_enum(223);
    pub const CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY: cudaError_enum = cudaError_enum(224);
    pub const CUDA_ERROR_INVALID_SOURCE: cudaError_enum = cudaError_enum(300);
    pub const CUDA_ERROR_FILE_NOT_FOUND: cudaError_enum = cudaError_enum(301);
    pub const CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND: cudaError_enum = cudaError_enum(302);
    pub const CUDA_ERROR_SHARED_OBJECT_INIT_FAILED: cudaError_enum = cudaError_enum(303);
    pub const CUDA_ERROR_OPERATING_SYSTEM: cudaError_enum = cudaError_enum(304);
    pub const CUDA_ERROR_INVALID_HANDLE: cudaError_enum = cudaError_enum(400);
    pub const CUDA_ERROR_ILLEGAL_STATE: cudaError_enum = cudaError_enum(401);
    pub const CUDA_ERROR_NOT_FOUND: cudaError_enum = cudaError_enum(500);
    pub const CUDA_ERROR_NOT_READY: cudaError_enum = cudaError_enum(600);
    pub const CUDA_ERROR_ILLEGAL_ADDRESS: cudaError_enum = cudaError_enum(700);
    pub const CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES: cudaError_enum = cudaError_enum(701);
    pub const CUDA_ERROR_LAUNCH_TIMEOUT: cudaError_enum = cudaError_enum(702);
    pub const CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING: cudaError_enum = cudaError_enum(703);
    pub const CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED: cudaError_enum = cudaError_enum(704);
    pub const CUDA_ERROR_PEER_ACCESS_NOT_ENABLED: cudaError_enum = cudaError_enum(705);
    pub const CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE: cudaError_enum = cudaError_enum(708);
    pub const CUDA_ERROR_CONTEXT_IS_DESTROYED: cudaError_enum = cudaError_enum(709);
    pub const CUDA_ERROR_ASSERT: cudaError_enum = cudaError_enum(710);
    pub const CUDA_ERROR_TOO_MANY_PEERS: cudaError_enum = cudaError_enum(711);
    pub const CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED: cudaError_enum = cudaError_enum(712);
    pub const CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED: cudaError_enum = cudaError_enum(713);
    pub const CUDA_ERROR_HARDWARE_STACK_ERROR: cudaError_enum = cudaError_enum(714);
    pub const CUDA_ERROR_ILLEGAL_INSTRUCTION: cudaError_enum = cudaError_enum(715);
    pub const CUDA_ERROR_MISALIGNED_ADDRESS: cudaError_enum = cudaError_enum(716);
    pub const CUDA_ERROR_INVALID_ADDRESS_SPACE: cudaError_enum = cudaError_enum(717);
    pub const CUDA_ERROR_INVALID_PC: cudaError_enum = cudaError_enum(718);
    pub const CUDA_ERROR_LAUNCH_FAILED: cudaError_enum = cudaError_enum(719);
    pub const CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE: cudaError_enum = cudaError_enum(720);
    pub const CUDA_ERROR_NOT_PERMITTED: cudaError_enum = cudaError_enum(800);
    pub const CUDA_ERROR_NOT_SUPPORTED: cudaError_enum = cudaError_enum(801);
    pub const CUDA_ERROR_SYSTEM_NOT_READY: cudaError_enum = cudaError_enum(802);
    pub const CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: cudaError_enum = cudaError_enum(803);
    pub const CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: cudaError_enum = cudaError_enum(804);
    pub const CUDA_ERROR_MPS_CONNECTION_FAILED: cudaError_enum = cudaError_enum(805);
    pub const CUDA_ERROR_MPS_RPC_FAILURE: cudaError_enum = cudaError_enum(806);
    pub const CUDA_ERROR_MPS_SERVER_NOT_READY: cudaError_enum = cudaError_enum(807);
    pub const CUDA_ERROR_MPS_MAX_CLIENTS_REACHED: cudaError_enum = cudaError_enum(808);
    pub const CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED: cudaError_enum = cudaError_enum(809);
    pub const CUDA_ERROR_MPS_CLIENT_TERMINATED: cudaError_enum = cudaError_enum(810);
    pub const CUDA_ERROR_CDP_NOT_SUPPORTED: cudaError_enum = cudaError_enum(811);
    pub const CUDA_ERROR_CDP_VERSION_MISMATCH: cudaError_enum = cudaError_enum(812);
    pub const CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED: cudaError_enum = cudaError_enum(900);
    pub const CUDA_ERROR_STREAM_CAPTURE_INVALIDATED: cudaError_enum = cudaError_enum(901);
    pub const CUDA_ERROR_STREAM_CAPTURE_MERGE: cudaError_enum = cudaError_enum(902);
    pub const CUDA_ERROR_STREAM_CAPTURE_UNMATCHED: cudaError_enum = cudaError_enum(903);
    pub const CUDA_ERROR_STREAM_CAPTURE_UNJOINED: cudaError_enum = cudaError_enum(904);
    pub const CUDA_ERROR_STREAM_CAPTURE_ISOLATION: cudaError_enum = cudaError_enum(905);
    pub const CUDA_ERROR_STREAM_CAPTURE_IMPLICIT: cudaError_enum = cudaError_enum(906);
    pub const CUDA_ERROR_CAPTURED_EVENT: cudaError_enum = cudaError_enum(907);
    pub const CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD: cudaError_enum = cudaError_enum(908);
    pub const CUDA_ERROR_TIMEOUT: cudaError_enum = cudaError_enum(909);
    pub const CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE: cudaError_enum = cudaError_enum(910);
    pub const CUDA_ERROR_EXTERNAL_DEVICE: cudaError_enum = cudaError_enum(911);
    pub const CUDA_ERROR_INVALID_CLUSTER_SIZE: cudaError_enum = cudaError_enum(912);
    pub const CUDA_ERROR_UNKNOWN: cudaError_enum = cudaError_enum(999);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct cudaError_enum(pub ::std::os::raw::c_uint);
pub use self::cudaError_enum as CUresult;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_MEMCPY2D_st {
    pub srcXInBytes: usize,
    pub srcY: usize,
    pub srcMemoryType: CUmemorytype,
    pub srcHost: *const ::std::os::raw::c_void,
    pub srcDevice: CUdeviceptr,
    pub srcArray: CUarray,
    pub srcPitch: usize,
    pub dstXInBytes: usize,
    pub dstY: usize,
    pub dstMemoryType: CUmemorytype,
    pub dstHost: *mut ::std::os::raw::c_void,
    pub dstDevice: CUdeviceptr,
    pub dstArray: CUarray,
    pub dstPitch: usize,
    pub WidthInBytes: usize,
    pub Height: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_MEMCPY2D_st"][::std::mem::size_of::<CUDA_MEMCPY2D_st>() - 128usize];
    ["Alignment of CUDA_MEMCPY2D_st"][::std::mem::align_of::<CUDA_MEMCPY2D_st>() - 8usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcXInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcXInBytes) - 0usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcY"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcY) - 8usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcMemoryType"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcMemoryType) - 16usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcHost"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcHost) - 24usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcDevice"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcDevice) - 32usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcArray"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcArray) - 40usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcPitch"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcPitch) - 48usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstXInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstXInBytes) - 56usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstY"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstY) - 64usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstMemoryType"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstMemoryType) - 72usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstHost"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstHost) - 80usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstDevice"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstDevice) - 88usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstArray"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstArray) - 96usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstPitch"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstPitch) - 104usize];
    ["Offset of field: CUDA_MEMCPY2D_st::WidthInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, WidthInBytes) - 112usize];
    ["Offset of field: CUDA_MEMCPY2D_st::Height"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, Height) - 120usize];
};
impl Default for CUDA_MEMCPY2D_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_MEMCPY2D_v2 = CUDA_MEMCPY2D_st;
pub type CUDA_MEMCPY2D = CUDA_MEMCPY2D_v2;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_ARRAY3D_DESCRIPTOR_st {
    pub Width: usize,
    pub Height: usize,
    pub Depth: usize,
    pub Format: CUarray_format,
    pub NumChannels: ::std::os::raw::c_uint,
    pub Flags: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_ARRAY3D_DESCRIPTOR_st"]
        [::std::mem::size_of::<CUDA_ARRAY3D_DESCRIPTOR_st>() - 40usize];
    ["Alignment of CUDA_ARRAY3D_DESCRIPTOR_st"]
        [::std::mem::align_of::<CUDA_ARRAY3D_DESCRIPTOR_st>() - 8usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Width"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Width) - 0usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Height"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Height) - 8usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Depth"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Depth) - 16usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Format"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Format) - 24usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::NumChannels"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, NumChannels) - 28usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Flags"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Flags) - 32usize];
};
impl Default for CUDA_ARRAY3D_DESCRIPTOR_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_ARRAY3D_DESCRIPTOR_v2 = CUDA_ARRAY3D_DESCRIPTOR_st;
pub type CUDA_ARRAY3D_DESCRIPTOR = CUDA_ARRAY3D_DESCRIPTOR_v2;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st {
    pub resType: CUresourcetype,
    pub res: CUDA_RESOURCE_DESC_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_RESOURCE_DESC_st__bindgen_ty_1 {
    pub array: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    pub mipmap: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2,
    pub linear: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
    pub pitch2D: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
    pub reserved: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub hArray: CUarray,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1::hArray"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        hArray
    ) - 0usize];
};
impl Default for CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2 {
    pub hMipmappedArray: CUmipmappedArray,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2::hMipmappedArray"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2,
        hMipmappedArray
    )
        - 0usize];
};
impl Default for CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3 {
    pub devPtr: CUdeviceptr,
    pub format: CUarray_format,
    pub numChannels: ::std::os::raw::c_uint,
    pub sizeInBytes: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3>() - 24usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::devPtr"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        devPtr
    ) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::format"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        format
    ) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::numChannels"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        numChannels
    )
        - 12usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::sizeInBytes"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        sizeInBytes
    )
        - 16usize];
};
impl Default for CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4 {
    pub devPtr: CUdeviceptr,
    pub format: CUarray_format,
    pub numChannels: ::std::os::raw::c_uint,
    pub width: usize,
    pub height: usize,
    pub pitchInBytes: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4>() - 40usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::devPtr"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        devPtr
    ) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::format"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        format
    ) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::numChannels"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        numChannels
    )
        - 12usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::width"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        width
    ) - 16usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::height"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        height
    ) - 24usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::pitchInBytes"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        pitchInBytes
    )
        - 32usize];
};
impl Default for CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5 {
    pub reserved: [::std::os::raw::c_int; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5>() - 128usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5>() - 4usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5::reserved"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5,
        reserved
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1>() - 128usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::array"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, array) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::mipmap"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, mipmap) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::linear"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, linear) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::pitch2D"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, pitch2D) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::reserved"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, reserved) - 0usize];
};
impl Default for CUDA_RESOURCE_DESC_st__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st"][::std::mem::size_of::<CUDA_RESOURCE_DESC_st>() - 144usize];
    ["Alignment of CUDA_RESOURCE_DESC_st"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::resType"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, resType) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::res"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, res) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, flags) - 136usize];
};
impl Default for CUDA_RESOURCE_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_RESOURCE_DESC_v1 = CUDA_RESOURCE_DESC_st;
pub type CUDA_RESOURCE_DESC = CUDA_RESOURCE_DESC_v1;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, PartialEq)]
pub struct CUDA_TEXTURE_DESC_st {
    pub addressMode: [CUaddress_mode; 3usize],
    pub filterMode: CUfilter_mode,
    pub flags: ::std::os::raw::c_uint,
    pub maxAnisotropy: ::std::os::raw::c_uint,
    pub mipmapFilterMode: CUfilter_mode,
    pub mipmapLevelBias: f32,
    pub minMipmapLevelClamp: f32,
    pub maxMipmapLevelClamp: f32,
    pub borderColor: [f32; 4usize],
    pub reserved: [::std::os::raw::c_int; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_TEXTURE_DESC_st"][::std::mem::size_of::<CUDA_TEXTURE_DESC_st>() - 104usize];
    ["Alignment of CUDA_TEXTURE_DESC_st"][::std::mem::align_of::<CUDA_TEXTURE_DESC_st>() - 4usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::addressMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, addressMode) - 0usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::filterMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, filterMode) - 12usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, flags) - 16usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::maxAnisotropy"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, maxAnisotropy) - 20usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::mipmapFilterMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, mipmapFilterMode) - 24usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::mipmapLevelBias"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, mipmapLevelBias) - 28usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::minMipmapLevelClamp"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, minMipmapLevelClamp) - 32usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::maxMipmapLevelClamp"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, maxMipmapLevelClamp) - 36usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::borderColor"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, borderColor) - 40usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, reserved) - 56usize];
};
impl Default for CUDA_TEXTURE_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_TEXTURE_DESC_v1 = CUDA_TEXTURE_DESC_st;
pub type CUDA_TEXTURE_DESC = CUDA_TEXTURE_DESC_v1;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUresourceViewFormat_enum {
    CU_RES_VIEW_FORMAT_NONE = 0,
    CU_RES_VIEW_FORMAT_UINT_1X8 = 1,
    CU_RES_VIEW_FORMAT_UINT_2X8 = 2,
    CU_RES_VIEW_FORMAT_UINT_4X8 = 3,
    CU_RES_VIEW_FORMAT_SINT_1X8 = 4,
    CU_RES_VIEW_FORMAT_SINT_2X8 = 5,
    CU_RES_VIEW_FORMAT_SINT_4X8 = 6,
    CU_RES_VIEW_FORMAT_UINT_1X16 = 7,
    CU_RES_VIEW_FORMAT_UINT_2X16 = 8,
    CU_RES_VIEW_FORMAT_UINT_4X16 = 9,
    CU_RES_VIEW_FORMAT_SINT_1X16 = 10,
    CU_RES_VIEW_FORMAT_SINT_2X16 = 11,
    CU_RES_VIEW_FORMAT_SINT_4X16 = 12,
    CU_RES_VIEW_FORMAT_UINT_1X32 = 13,
    CU_RES_VIEW_FORMAT_UINT_2X32 = 14,
    CU_RES_VIEW_FORMAT_UINT_4X32 = 15,
    CU_RES_VIEW_FORMAT_SINT_1X32 = 16,
    CU_RES_VIEW_FORMAT_SINT_2X32 = 17,
    CU_RES_VIEW_FORMAT_SINT_4X32 = 18,
    CU_RES_VIEW_FORMAT_FLOAT_1X16 = 19,
    CU_RES_VIEW_FORMAT_FLOAT_2X16 = 20,
    CU_RES_VIEW_FORMAT_FLOAT_4X16 = 21,
    CU_RES_VIEW_FORMAT_FLOAT_1X32 = 22,
    CU_RES_VIEW_FORMAT_FLOAT_2X32 = 23,
    CU_RES_VIEW_FORMAT_FLOAT_4X32 = 24,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC1 = 25,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC2 = 26,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC3 = 27,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC4 = 28,
    CU_RES_VIEW_FORMAT_SIGNED_BC4 = 29,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC5 = 30,
    CU_RES_VIEW_FORMAT_SIGNED_BC5 = 31,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC6H = 32,
    CU_RES_VIEW_FORMAT_SIGNED_BC6H = 33,
    CU_RES_VIEW_FORMAT_UNSIGNED_BC7 = 34,
}
pub use self::CUresourceViewFormat_enum as CUresourceViewFormat;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_RESOURCE_VIEW_DESC_st {
    pub format: CUresourceViewFormat,
    pub width: usize,
    pub height: usize,
    pub depth: usize,
    pub firstMipmapLevel: ::std::os::raw::c_uint,
    pub lastMipmapLevel: ::std::os::raw::c_uint,
    pub firstLayer: ::std::os::raw::c_uint,
    pub lastLayer: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_VIEW_DESC_st"]
        [::std::mem::size_of::<CUDA_RESOURCE_VIEW_DESC_st>() - 112usize];
    ["Alignment of CUDA_RESOURCE_VIEW_DESC_st"]
        [::std::mem::align_of::<CUDA_RESOURCE_VIEW_DESC_st>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::format"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, format) - 0usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::width"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, width) - 8usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::height"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, height) - 16usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::depth"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, depth) - 24usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::firstMipmapLevel"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, firstMipmapLevel) - 32usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::lastMipmapLevel"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, lastMipmapLevel) - 36usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::firstLayer"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, firstLayer) - 40usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::lastLayer"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, lastLayer) - 44usize];
    ["Offset of field: CUDA_RESOURCE_VIEW_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_RESOURCE_VIEW_DESC_st, reserved) - 48usize];
};
impl Default for CUDA_RESOURCE_VIEW_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_RESOURCE_VIEW_DESC_v1 = CUDA_RESOURCE_VIEW_DESC_st;
pub type CUDA_RESOURCE_VIEW_DESC = CUDA_RESOURCE_VIEW_DESC_v1;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUexternalMemoryHandleType_enum {
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD = 1,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32 = 2,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT = 3,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP = 4,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE = 5,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_RESOURCE = 6,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_RESOURCE_KMT = 7,
    CU_EXTERNAL_MEMORY_HANDLE_TYPE_NVSCIBUF = 8,
}
pub use self::CUexternalMemoryHandleType_enum as CUexternalMemoryHandleType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st {
    pub type_: CUexternalMemoryHandleType,
    pub handle: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1,
    pub size: ::std::os::raw::c_ulonglong,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1 {
    pub fd: ::std::os::raw::c_int,
    pub win32: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    pub nvSciBufObject: *const ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub handle: *mut ::std::os::raw::c_void,
    pub name: *const ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"][::std::mem::size_of::<
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    >() - 16usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>()
            - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::handle"][::std::mem::offset_of!(
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        handle
    )
        - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::name"][::std::mem::offset_of!(
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        name
    )
        - 8usize];
};
impl Default for CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1>() - 16usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1::fd"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1, fd) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1::win32"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1, win32) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1::nvSciBufObject"][::std::mem::offset_of!(
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1,
        nvSciBufObject
    )
        - 0usize];
};
impl Default for CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st>() - 104usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::type_"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, type_) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::handle"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, handle) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::size"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, size) - 24usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, flags) - 32usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, reserved) - 36usize];
};
impl Default for CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_EXTERNAL_MEMORY_HANDLE_DESC_v1 = CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st;
pub type CUDA_EXTERNAL_MEMORY_HANDLE_DESC = CUDA_EXTERNAL_MEMORY_HANDLE_DESC_v1;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st {
    pub offset: ::std::os::raw::c_ulonglong,
    pub size: ::std::os::raw::c_ulonglong,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st>() - 88usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::offset"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, offset) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::size"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, size) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, flags) - 16usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, reserved) - 20usize];
};
pub type CUDA_EXTERNAL_MEMORY_BUFFER_DESC_v1 = CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st;
pub type CUDA_EXTERNAL_MEMORY_BUFFER_DESC = CUDA_EXTERNAL_MEMORY_BUFFER_DESC_v1;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st {
    pub offset: ::std::os::raw::c_ulonglong,
    pub arrayDesc: CUDA_ARRAY3D_DESCRIPTOR,
    pub numLevels: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st>() - 120usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::offset"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, offset) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::arrayDesc"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, arrayDesc) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::numLevels"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, numLevels) - 48usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, reserved) - 52usize];
};
impl Default for CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_v1 =
    CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st;
pub type CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC = CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_v1;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum CUexternalSemaphoreHandleType_enum {
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD = 1,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32 = 2,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT = 3,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE = 4,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_FENCE = 5,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_NVSCISYNC = 6,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_KEYED_MUTEX = 7,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_KEYED_MUTEX_KMT = 8,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_FD = 9,
    CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_WIN32 = 10,
}
pub use self::CUexternalSemaphoreHandleType_enum as CUexternalSemaphoreHandleType;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st {
    pub type_: CUexternalSemaphoreHandleType,
    pub handle: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1 {
    pub fd: ::std::os::raw::c_int,
    pub win32: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    pub nvSciSyncObj: *const ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub handle: *mut ::std::os::raw::c_void,
    pub name: *const ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 16usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::handle"]
        [::std::mem::offset_of!(
            CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
            handle
        ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::name"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        name
    )
        - 8usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1>() - 16usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1::fd"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1, fd) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1::win32"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1,
        win32
    ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1::nvSciSyncObj"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1,
        nvSciSyncObj
    )
        - 0usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st>() - 96usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::type_"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, type_) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::handle"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, handle) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, flags) - 24usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, reserved) - 28usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_v1 = CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st;
pub type CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC = CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_v1;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st {
    pub params: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1 {
    pub fence: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
    pub nvSciSync: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
    pub keyedMutex: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
    pub reserved: [::std::os::raw::c_uint; 12usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1 {
    pub value: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<
            CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
        >() - 8usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1::value",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
        value
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2 {
    pub fence: *mut ::std::os::raw::c_void,
    pub reserved: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<
            CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
        >() - 8usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2::fence",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
        fence
    ) - 0usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2::reserved",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
        reserved
    ) - 0usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3 {
    pub key: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<
            CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
        >() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3::key"]
        [::std::mem::offset_of!(
            CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
            key
        ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1>() - 72usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::fence"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        fence
    ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::nvSciSync"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        nvSciSync
    )
        - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::keyedMutex"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        keyedMutex
    )
        - 16usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::reserved"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        reserved
    )
        - 24usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st>() - 144usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::params"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, params) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, flags) - 72usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, reserved) - 76usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_v1 = CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st;
pub type CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS = CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_v1;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st {
    pub params: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1 {
    pub fence: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
    pub nvSciSync: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
    pub keyedMutex: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
    pub reserved: [::std::os::raw::c_uint; 10usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1 {
    pub value: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1::value"]
        [::std::mem::offset_of!(
            CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
            value
        ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2 {
    pub fence: *mut ::std::os::raw::c_void,
    pub reserved: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2>(
        ) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2::fence"]
        [::std::mem::offset_of!(
            CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
            fence
        ) - 0usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2::reserved",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2,
        reserved
    ) - 0usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3 {
    pub key: ::std::os::raw::c_ulonglong,
    pub timeoutMs: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3>(
        ) - 16usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3>(
        ) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3::key"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
        key
    )
        - 0usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3::timeoutMs",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1__bindgen_ty_3,
        timeoutMs
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1>() - 72usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1::fence"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1,
        fence
    ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1::nvSciSync"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1,
        nvSciSync
    )
        - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1::keyedMutex"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1,
        keyedMutex
    )
        - 16usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1::reserved"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1,
        reserved
    )
        - 32usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st>() - 144usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st::params"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st, params) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st, flags) - 72usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st, reserved) - 76usize];
};
impl Default for CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_v1 = CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st;
pub type CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS = CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_v1;
unsafe extern "C" {
    pub fn cuGetErrorString(error: CUresult, pStr: *mut *const ::std::os::raw::c_char) -> CUresult;
}
unsafe extern "C" {
    pub fn cuGetErrorName(error: CUresult, pStr: *mut *const ::std::os::raw::c_char) -> CUresult;
}
unsafe extern "C" {
    pub fn cuInit(Flags: ::std::os::raw::c_uint) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDeviceGet(device: *mut CUdevice, ordinal: ::std::os::raw::c_int) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDeviceGetCount(count: *mut ::std::os::raw::c_int) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDeviceGetName(
        name: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        dev: CUdevice,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDeviceGetUuid(uuid: *mut CUuuid, dev: CUdevice) -> CUresult;
}
unsafe extern "C" {
    pub fn cuCtxCreate_v2(
        pctx: *mut CUcontext,
        flags: ::std::os::raw::c_uint,
        dev: CUdevice,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuCtxDestroy_v2(ctx: CUcontext) -> CUresult;
}
unsafe extern "C" {
    pub fn cuCtxPushCurrent_v2(ctx: CUcontext) -> CUresult;
}
unsafe extern "C" {
    pub fn cuCtxPopCurrent_v2(pctx: *mut CUcontext) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemAllocPitch_v2(
        dptr: *mut CUdeviceptr,
        pPitch: *mut usize,
        WidthInBytes: usize,
        Height: usize,
        ElementSizeBytes: ::std::os::raw::c_uint,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemFree_v2(dptr: CUdeviceptr) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemAllocHost_v2(pp: *mut *mut ::std::os::raw::c_void, bytesize: usize) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemFreeHost(p: *mut ::std::os::raw::c_void) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemcpyDtoH_v2(
        dstHost: *mut ::std::os::raw::c_void,
        srcDevice: CUdeviceptr,
        ByteCount: usize,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemcpy2D_v2(pCopy: *const CUDA_MEMCPY2D) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemcpy2DUnaligned_v2(pCopy: *const CUDA_MEMCPY2D) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMemcpy2DAsync_v2(pCopy: *const CUDA_MEMCPY2D, hStream: CUstream) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMipmappedArrayGetLevel(
        pLevelArray: *mut CUarray,
        hMipmappedArray: CUmipmappedArray,
        level: ::std::os::raw::c_uint,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuMipmappedArrayDestroy(hMipmappedArray: CUmipmappedArray) -> CUresult;
}
unsafe extern "C" {
    pub fn cuStreamCreate(phStream: *mut CUstream, Flags: ::std::os::raw::c_uint) -> CUresult;
}
unsafe extern "C" {
    pub fn cuStreamDestroy_v2(hStream: CUstream) -> CUresult;
}
unsafe extern "C" {
    pub fn cuImportExternalMemory(
        extMem_out: *mut CUexternalMemory,
        memHandleDesc: *const CUDA_EXTERNAL_MEMORY_HANDLE_DESC,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuExternalMemoryGetMappedBuffer(
        devPtr: *mut CUdeviceptr,
        extMem: CUexternalMemory,
        bufferDesc: *const CUDA_EXTERNAL_MEMORY_BUFFER_DESC,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuExternalMemoryGetMappedMipmappedArray(
        mipmap: *mut CUmipmappedArray,
        extMem: CUexternalMemory,
        mipmapDesc: *const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDestroyExternalMemory(extMem: CUexternalMemory) -> CUresult;
}
unsafe extern "C" {
    pub fn cuImportExternalSemaphore(
        extSem_out: *mut CUexternalSemaphore,
        semHandleDesc: *const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuSignalExternalSemaphoresAsync(
        extSemArray: *const CUexternalSemaphore,
        paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS,
        numExtSems: ::std::os::raw::c_uint,
        stream: CUstream,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuWaitExternalSemaphoresAsync(
        extSemArray: *const CUexternalSemaphore,
        paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS,
        numExtSems: ::std::os::raw::c_uint,
        stream: CUstream,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuDestroyExternalSemaphore(extSem: CUexternalSemaphore) -> CUresult;
}
unsafe extern "C" {
    pub fn cuTexObjectCreate(
        pTexObject: *mut CUtexObject,
        pResDesc: *const CUDA_RESOURCE_DESC,
        pTexDesc: *const CUDA_TEXTURE_DESC,
        pResViewDesc: *const CUDA_RESOURCE_VIEW_DESC,
    ) -> CUresult;
}
unsafe extern "C" {
    pub fn cuTexObjectDestroy(texObject: CUtexObject) -> CUresult;
}
