/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

//! FFI bindings for VA-API: the types, enums, and constants of the bundled libva headers
//! (`headers/`, VA-API 1.24), generated by bindgen and committed under `src/bindgen/`, and a
//! table of the entry points pixelflux calls, resolved from the host's `libva.so.2` and
//! `libva-drm.so.2` at run time. Nothing links libva: the wheel leaves the host's copy in
//! charge of the driver it was built for, and a test can fill the table with functions of its
//! own. Regenerate the types after a header bump with `cargo build --features regen`
//! (needs libclang).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]
#![allow(unnecessary_transmutes)]
#![allow(unsafe_op_in_unsafe_fn)]

use std::ffi::{c_char, c_int, c_uint, c_void};

use libloading::Library;

include!("bindgen/va.rs");

/// The libva entry points a session calls, in the host library's own signatures.
#[derive(Clone, Copy)]
pub struct VaApi {
    pub vaErrorStr: unsafe extern "C" fn(VAStatus) -> *const c_char,
    pub vaSetErrorCallback: unsafe extern "C" fn(VADisplay, VAMessageCallback, *mut c_void) -> VAMessageCallback,
    pub vaSetInfoCallback: unsafe extern "C" fn(VADisplay, VAMessageCallback, *mut c_void) -> VAMessageCallback,
    pub vaInitialize: unsafe extern "C" fn(VADisplay, *mut c_int, *mut c_int) -> VAStatus,
    pub vaTerminate: unsafe extern "C" fn(VADisplay) -> VAStatus,
    pub vaQueryVendorString: unsafe extern "C" fn(VADisplay) -> *const c_char,
    pub vaMaxNumProfiles: unsafe extern "C" fn(VADisplay) -> c_int,
    pub vaMaxNumEntrypoints: unsafe extern "C" fn(VADisplay) -> c_int,
    pub vaMaxNumImageFormats: unsafe extern "C" fn(VADisplay) -> c_int,
    pub vaQueryConfigProfiles: unsafe extern "C" fn(VADisplay, *mut VAProfile, *mut c_int) -> VAStatus,
    pub vaQueryConfigEntrypoints:
        unsafe extern "C" fn(VADisplay, VAProfile, *mut VAEntrypoint, *mut c_int) -> VAStatus,
    pub vaGetConfigAttributes:
        unsafe extern "C" fn(VADisplay, VAProfile, VAEntrypoint, *mut VAConfigAttrib, c_int) -> VAStatus,
    pub vaCreateConfig: unsafe extern "C" fn(
        VADisplay,
        VAProfile,
        VAEntrypoint,
        *mut VAConfigAttrib,
        c_int,
        *mut VAConfigID,
    ) -> VAStatus,
    pub vaDestroyConfig: unsafe extern "C" fn(VADisplay, VAConfigID) -> VAStatus,
    pub vaQuerySurfaceAttributes:
        unsafe extern "C" fn(VADisplay, VAConfigID, *mut VASurfaceAttrib, *mut c_uint) -> VAStatus,
    pub vaCreateSurfaces: unsafe extern "C" fn(
        VADisplay,
        c_uint,
        c_uint,
        c_uint,
        *mut VASurfaceID,
        c_uint,
        *mut VASurfaceAttrib,
        c_uint,
    ) -> VAStatus,
    pub vaDestroySurfaces: unsafe extern "C" fn(VADisplay, *mut VASurfaceID, c_int) -> VAStatus,
    pub vaCreateContext: unsafe extern "C" fn(
        VADisplay,
        VAConfigID,
        c_int,
        c_int,
        c_int,
        *mut VASurfaceID,
        c_int,
        *mut VAContextID,
    ) -> VAStatus,
    pub vaDestroyContext: unsafe extern "C" fn(VADisplay, VAContextID) -> VAStatus,
    pub vaCreateBuffer: unsafe extern "C" fn(
        VADisplay,
        VAContextID,
        VABufferType,
        c_uint,
        c_uint,
        *mut c_void,
        *mut VABufferID,
    ) -> VAStatus,
    pub vaMapBuffer: unsafe extern "C" fn(VADisplay, VABufferID, *mut *mut c_void) -> VAStatus,
    pub vaUnmapBuffer: unsafe extern "C" fn(VADisplay, VABufferID) -> VAStatus,
    pub vaDestroyBuffer: unsafe extern "C" fn(VADisplay, VABufferID) -> VAStatus,
    pub vaBeginPicture: unsafe extern "C" fn(VADisplay, VAContextID, VASurfaceID) -> VAStatus,
    pub vaRenderPicture: unsafe extern "C" fn(VADisplay, VAContextID, *mut VABufferID, c_int) -> VAStatus,
    pub vaEndPicture: unsafe extern "C" fn(VADisplay, VAContextID) -> VAStatus,
    pub vaSyncSurface: unsafe extern "C" fn(VADisplay, VASurfaceID) -> VAStatus,
    /// Absent before VA-API 1.9; a driver may also answer it unimplemented.
    pub vaSyncBuffer: Option<unsafe extern "C" fn(VADisplay, VABufferID, u64) -> VAStatus>,
    pub vaQueryImageFormats: unsafe extern "C" fn(VADisplay, *mut VAImageFormat, *mut c_int) -> VAStatus,
    pub vaCreateImage: unsafe extern "C" fn(VADisplay, *mut VAImageFormat, c_int, c_int, *mut VAImage) -> VAStatus,
    pub vaDestroyImage: unsafe extern "C" fn(VADisplay, VAImageID) -> VAStatus,
    pub vaPutImage: unsafe extern "C" fn(
        VADisplay,
        VASurfaceID,
        VAImageID,
        c_int,
        c_int,
        c_uint,
        c_uint,
        c_int,
        c_int,
        c_uint,
        c_uint,
    ) -> VAStatus,
    pub vaDeriveImage: unsafe extern "C" fn(VADisplay, VASurfaceID, *mut VAImage) -> VAStatus,
    pub vaQueryVideoProcPipelineCaps:
        unsafe extern "C" fn(VADisplay, VAContextID, *mut VABufferID, c_uint, *mut VAProcPipelineCaps) -> VAStatus,
    /// `vaGetDisplayDRM` of `libva-drm.so.2`: the display of an open DRM render node.
    pub vaGetDisplayDRM: unsafe extern "C" fn(c_int) -> VADisplay,
}

/// The sonames the table is resolved from, the ones every VA-API driver's own libva links.
pub const LIBVA: &str = "libva.so.2";
pub const LIBVA_DRM: &str = "libva-drm.so.2";

/// The loaded libraries and the table resolved from them; the table stays valid while this
/// lives.
pub struct Libva {
    pub api: VaApi,
    _va: Library,
    _drm: Library,
}

impl Libva {
    /// Load `libva.so.2` and `libva-drm.so.2` and resolve every entry point of the table, or
    /// say which library or symbol the host lacks.
    ///
    /// # Safety
    /// Loading a shared library runs its initializers.
    pub unsafe fn load() -> Result<Self, String> {
        let va = unsafe { Library::new(LIBVA) }.map_err(|e| format!("{LIBVA}: {e}"))?;
        let drm = unsafe { Library::new(LIBVA_DRM) }.map_err(|e| format!("{LIBVA_DRM}: {e}"))?;
        macro_rules! sym {
            ($lib:expr, $name:ident) => {
                unsafe { $lib.get::<unsafe extern "C" fn()>(concat!(stringify!($name), "\0").as_bytes()) }
                    .map(|s| unsafe { std::mem::transmute(*s) })
                    .map_err(|e| format!("{}: {e}", stringify!($name)))?
            };
        }
        let api = VaApi {
            vaErrorStr: sym!(va, vaErrorStr),
            vaSetErrorCallback: sym!(va, vaSetErrorCallback),
            vaSetInfoCallback: sym!(va, vaSetInfoCallback),
            vaInitialize: sym!(va, vaInitialize),
            vaTerminate: sym!(va, vaTerminate),
            vaQueryVendorString: sym!(va, vaQueryVendorString),
            vaMaxNumProfiles: sym!(va, vaMaxNumProfiles),
            vaMaxNumEntrypoints: sym!(va, vaMaxNumEntrypoints),
            vaMaxNumImageFormats: sym!(va, vaMaxNumImageFormats),
            vaQueryConfigProfiles: sym!(va, vaQueryConfigProfiles),
            vaQueryConfigEntrypoints: sym!(va, vaQueryConfigEntrypoints),
            vaGetConfigAttributes: sym!(va, vaGetConfigAttributes),
            vaCreateConfig: sym!(va, vaCreateConfig),
            vaDestroyConfig: sym!(va, vaDestroyConfig),
            vaQuerySurfaceAttributes: sym!(va, vaQuerySurfaceAttributes),
            vaCreateSurfaces: sym!(va, vaCreateSurfaces),
            vaDestroySurfaces: sym!(va, vaDestroySurfaces),
            vaCreateContext: sym!(va, vaCreateContext),
            vaDestroyContext: sym!(va, vaDestroyContext),
            vaCreateBuffer: sym!(va, vaCreateBuffer),
            vaMapBuffer: sym!(va, vaMapBuffer),
            vaUnmapBuffer: sym!(va, vaUnmapBuffer),
            vaDestroyBuffer: sym!(va, vaDestroyBuffer),
            vaBeginPicture: sym!(va, vaBeginPicture),
            vaRenderPicture: sym!(va, vaRenderPicture),
            vaEndPicture: sym!(va, vaEndPicture),
            vaSyncSurface: sym!(va, vaSyncSurface),
            vaSyncBuffer: unsafe { va.get::<unsafe extern "C" fn(VADisplay, VABufferID, u64) -> VAStatus>(b"vaSyncBuffer\0") }
                .ok()
                .map(|s| *s),
            vaQueryImageFormats: sym!(va, vaQueryImageFormats),
            vaCreateImage: sym!(va, vaCreateImage),
            vaDestroyImage: sym!(va, vaDestroyImage),
            vaPutImage: sym!(va, vaPutImage),
            vaDeriveImage: sym!(va, vaDeriveImage),
            vaQueryVideoProcPipelineCaps: sym!(va, vaQueryVideoProcPipelineCaps),
            vaGetDisplayDRM: sym!(drm, vaGetDisplayDRM),
        };
        Ok(Self { api, _va: va, _drm: drm })
    }
}
